import type { MovieDetails } from '../../models/movie';

export const MOCK_MOVIES: MovieDetails[] = [
  {
    imdbID: 'tt1375666',
    Title: 'Inception',
    Year: '2010',
    Rated: 'PG-13',
    Released: '16 Jul 2010',
    Runtime: '148 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Christopher Nolan',
    Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
    Plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    Language: 'English, Japanese, French',
    Country: 'United States, United Kingdom',
    Awards: 'Won 4 Oscars. 159 wins & 220 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '87%' },
      { Source: 'Metacritic', Value: '74/100' }
    ],
    Metascore: '74',
    imdbRating: '8.8',
    imdbVotes: '2,580,000',
    Type: 'movie',
    BoxOffice: '$292,587,330'
  },
  {
    imdbID: 'tt0468569',
    Title: 'The Dark Knight',
    Year: '2008',
    Rated: 'PG-13',
    Released: '18 Jul 2008',
    Runtime: '152 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Christopher Nolan',
    Writer: 'Jonathan Nolan, Christopher Nolan, David S. Goyer',
    Actors: 'Christian Bale, Heath Ledger, Aaron Eckhart',
    Plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    Language: 'English, Mandarin',
    Country: 'United States, United Kingdom',
    Awards: 'Won 2 Oscars. 163 wins & 164 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.0/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '84/100' }
    ],
    Metascore: '84',
    imdbRating: '9.0',
    imdbVotes: '2,900,000',
    Type: 'movie',
    BoxOffice: '$534,987,076'
  },
  {
    imdbID: 'tt0816692',
    Title: 'Interstellar',
    Year: '2014',
    Rated: 'PG-13',
    Released: '07 Nov 2014',
    Runtime: '169 min',
    Genre: 'Adventure, Drama, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Jonathan Nolan, Christopher Nolan',
    Actors: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
    Plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    Language: 'English',
    Country: 'United States, United Kingdom, Canada',
    Awards: 'Won 1 Oscar. 44 wins & 148 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '73%' },
      { Source: 'Metacritic', Value: '74/100' }
    ],
    Metascore: '74',
    imdbRating: '8.7',
    imdbVotes: '2,100,000',
    Type: 'movie',
    BoxOffice: '$188,020,017'
  },
  {
    imdbID: 'tt1160419',
    Title: 'Dune: Part One',
    Year: '2021',
    Rated: 'PG-13',
    Released: '22 Oct 2021',
    Runtime: '155 min',
    Genre: 'Action, Adventure, Drama, Sci-Fi',
    Director: 'Denis Villeneuve',
    Writer: 'Jon Spaihts, Denis Villeneuve, Eric Roth',
    Actors: 'Timothée Chalamet, Rebecca Ferguson, Zendaya',
    Plot: 'A noble family becomes embroiled in a war for control over the galaxy\'s most valuable asset while its heir becomes troubled by visions of a dark future.',
    Language: 'English, Mandarin',
    Country: 'United States',
    Awards: 'Won 6 Oscars. 172 wins & 285 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.0/10' },
      { Source: 'Rotten Tomatoes', Value: '83%' },
      { Source: 'Metacritic', Value: '74/100' }
    ],
    Metascore: '74',
    imdbRating: '8.0',
    imdbVotes: '780,000',
    Type: 'movie',
    BoxOffice: '$108,327,830'
  },
  {
    imdbID: 'tt15398776',
    Title: 'Oppenheimer',
    Year: '2023',
    Rated: 'R',
    Released: '21 Jul 2023',
    Runtime: '180 min',
    Genre: 'Biography, Drama, History',
    Director: 'Christopher Nolan',
    Writer: 'Christopher Nolan, Kai Bird, Martin J. Sherwin',
    Actors: 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.',
    Plot: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    Language: 'English, German, Italian',
    Country: 'United States, United Kingdom',
    Awards: 'Won 7 Oscars. 343 wins & 382 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZmVhYi00ZTFmLTk5OGYtOWExNmFlOGZjMTliXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.9/10' },
      { Source: 'Rotten Tomatoes', Value: '93%' },
      { Source: 'Metacritic', Value: '88/100' }
    ],
    Metascore: '88',
    imdbRating: '8.9',
    imdbVotes: '810,000',
    Type: 'movie',
    BoxOffice: '$329,862,540'
  },
  {
    imdbID: 'tt9362722',
    Title: 'Spider-Man: Across the Spider-Verse',
    Year: '2023',
    Rated: 'PG',
    Released: '02 Jun 2023',
    Runtime: '140 min',
    Genre: 'Animation, Action, Adventure, Sci-Fi',
    Director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    Writer: 'Phil Lord, Christopher Miller, Dave Callaham',
    Actors: 'Shameik Moore, Hailee Steinfeld, Oscar Isaac',
    Plot: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
    Language: 'English, Spanish',
    Country: 'United States',
    Awards: 'Nominated for 1 Oscar. 92 wins & 157 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.6/10' },
      { Source: 'Rotten Tomatoes', Value: '95%' },
      { Source: 'Metacritic', Value: '86/100' }
    ],
    Metascore: '86',
    imdbRating: '8.6',
    imdbVotes: '390,000',
    Type: 'movie',
    BoxOffice: '$381,311,319'
  },
  {
    imdbID: 'tt0133093',
    Title: 'The Matrix',
    Year: '1999',
    Rated: 'R',
    Released: '31 Mar 1999',
    Runtime: '136 min',
    Genre: 'Action, Sci-Fi',
    Director: 'Lana Wachowski, Lilly Wachowski',
    Writer: 'Lilly Wachowski, Lana Wachowski',
    Actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
    Plot: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    Language: 'English',
    Country: 'United States, Australia',
    Awards: 'Won 4 Oscars. 42 wins & 52 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '83%' },
      { Source: 'Metacritic', Value: '73/100' }
    ],
    Metascore: '73',
    imdbRating: '8.7',
    imdbVotes: '2,080,000',
    Type: 'movie',
    BoxOffice: '$171,479,930'
  },
  {
    imdbID: 'tt4154796',
    Title: 'Avengers: Endgame',
    Year: '2019',
    Rated: 'PG-13',
    Released: '26 Apr 2019',
    Runtime: '181 min',
    Genre: 'Action, Adventure, Drama, Sci-Fi',
    Director: 'Anthony Russo, Joe Russo',
    Writer: 'Christopher Markus, Stephen McFeely, Stan Lee',
    Actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
    Plot: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
    Language: 'English, Japanese, Xhosa, German',
    Country: 'United States',
    Awards: 'Nominated for 1 Oscar. 70 wins & 133 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.4/10' },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '78/100' }
    ],
    Metascore: '78',
    imdbRating: '8.4',
    imdbVotes: '1,320,000',
    Type: 'movie',
    BoxOffice: '$858,373,000'
  },
  {
    imdbID: 'tt0903747',
    Title: 'Breaking Bad',
    Year: '2008–2013',
    Rated: 'TV-MA',
    Released: '20 Jan 2008',
    Runtime: '49 min',
    Genre: 'Crime, Drama, Thriller',
    Director: 'Vince Gilligan',
    Writer: 'Vince Gilligan',
    Actors: 'Bryan Cranston, Aaron Paul, Anna Gunn',
    Plot: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family\'s financial future.',
    Language: 'English, Spanish',
    Country: 'United States',
    Awards: 'Won 16 Primetime Emmys. 158 wins & 247 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.5/10' },
      { Source: 'Rotten Tomatoes', Value: '96%' }
    ],
    Metascore: 'N/A',
    imdbRating: '9.5',
    imdbVotes: '2,150,000',
    Type: 'series',
    totalSeasons: '5'
  },
  {
    imdbID: 'tt4574334',
    Title: 'Stranger Things',
    Year: '2016–2025',
    Rated: 'TV-14',
    Released: '15 Jul 2016',
    Runtime: '51 min',
    Genre: 'Drama, Fantasy, Horror, Sci-Fi',
    Director: 'Matt Duffer, Ross Duffer',
    Writer: 'Matt Duffer, Ross Duffer',
    Actors: 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
    Plot: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    Language: 'English, Russian',
    Country: 'United States',
    Awards: 'Won 12 Primetime Emmys. 104 wins & 246 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMDZkODY2NzItYzczNi00MDk0LTlhYjMtMDY0NzA0OWEzNGExXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.7/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' }
    ],
    Metascore: 'N/A',
    imdbRating: '8.7',
    imdbVotes: '1,380,000',
    Type: 'series',
    totalSeasons: '4'
  },
  {
    imdbID: 'tt0111161',
    Title: 'The Shawshank Redemption',
    Year: '1994',
    Rated: 'R',
    Released: '14 Oct 1994',
    Runtime: '142 min',
    Genre: 'Drama',
    Director: 'Frank Darabont',
    Writer: 'Stephen King, Frank Darabont',
    Actors: 'Tim Robbins, Morgan Freeman, Bob Gunton',
    Plot: 'A banker convicted of uxoricide forms a friendship over a quarter of a century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Nominated for 7 Oscars. 21 wins & 43 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2NDExXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '9.3/10' },
      { Source: 'Rotten Tomatoes', Value: '91%' },
      { Source: 'Metacritic', Value: '82/100' }
    ],
    Metascore: '82',
    imdbRating: '9.3',
    imdbVotes: '2,900,000',
    Type: 'movie',
    BoxOffice: '$28,767,189'
  },
  {
    imdbID: 'tt0109830',
    Title: 'Forrest Gump',
    Year: '1994',
    Rated: 'PG-13',
    Released: '06 Jul 1994',
    Runtime: '142 min',
    Genre: 'Drama, Romance',
    Director: 'Robert Zemeckis',
    Writer: 'Winston Groom, Eric Roth',
    Actors: 'Tom Hanks, Robin Wright, Gary Sinise',
    Plot: 'The history of the United States from the 1950s to the \'70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.',
    Language: 'English',
    Country: 'United States',
    Awards: 'Won 6 Oscars. 52 wins & 77 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.8/10' },
      { Source: 'Rotten Tomatoes', Value: '71%' },
      { Source: 'Metacritic', Value: '82/100' }
    ],
    Metascore: '82',
    imdbRating: '8.8',
    imdbVotes: '2,270,000',
    Type: 'movie',
    BoxOffice: '$330,455,270'
  }
];

export const HERO_FEATURED_MOVIE = MOCK_MOVIES[0];
